name: ModerationChat
version: 1.0.0
api: 5.0.0
main: Jorgebyte\moderationchat\Main
author: Jorgebyte
description: "Moderation Chat PocketMine-MP Api5"

permissions:
  moderationchat.admin:
    description: "admin chat"
    default: op
  moderationchat.command:
    description: "clear chat command"
    default: op
